index:
    path: /
    controller: PolemLasem\Shop\Controller\IndexController::index

static_page:
    path: /informacje/{slug}
    controller: PolemLasem\Shop\Controller\StaticPageController::page
    requirements:
        slug: '[a-z\-0-9]+'
